<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>11</LangVersion>
    <NoWarn>MSB3277,IDE0011,IDE0005,IDE0001,IDE0002,IDE0003,IDE0007,IDE0009,CA1707,CA1711,CA1051,CA1812,CA1815,CA1819,CA1825,CA1834,CA1838,CA2211,CA2227,CA1031,CS1591,RUST005,RUST003,RA0013,RA0030,RA0040,RA0050</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>disable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <DefaultItemExcludes>$(DefaultItemExcludes);build\**;RustServerManager\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="RustVersion" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include=".\Managed\*.dll">
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="rust-analyzer" Version="8.0.36">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="4.13.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SecurityCodeScan.VS2019" Version="5.6.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.6.0.109712">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SuggestMembersAnalyzer" Version="1.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="UnityEngineAnalyzer" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="./.rust-analyzer/deprecatedHooks.json" />
    <AdditionalFiles Include="./.rust-analyzer/hooks.json" />
    <AdditionalFiles Include="./.rust-analyzer/stringPool.json" />
    <AdditionalFiles Include="./.rust-analyzer/stringPoolMethods.json" />
    <AdditionalFiles Include="./.rust-analyzer/hooksPlugin.json" />
    <AdditionalFiles Include="./.rust-analyzer/apiMethodsPlugin.json" />
  </ItemGroup>
</Project>
